azure:
  free_disk_space: true
  store_build_artifacts: true
build_platform:
  linux_aarch64: linux_64
conda_build:
  error_overlinking: true
  pkg_format: '2'
  # Highest compression is 22. Increased compression to prevent timeout issue when
  # uploading packages. (Smaller package; less upload time)
  zstd_compression_level: 22
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
github_actions:
  self_hosted: true
  store_build_artifacts: true
  triggers:
  - push
  - pull_request
  timeout_minutes: 360
provider:
  linux_64: github_actions
  linux_aarch64: default
  win_64: github_actions
